Repository dusk-network/Poseidon252, pull requests merged in 2020-11, with the labels that each got.

#87 Update CI to fit with Canon
  .github/workflows/dusk_ci.yml
  rust-toolchain
Labels: area:testing

#89 Derive `Canon` for `PoseidonCipher`
  Cargo.toml
  src/cipher/cipher.rs
Labels: area:IPC, type:feature

#90 Add gate-featured `Canon` impl/usage
  .github/workflows/dusk_ci.yml
  CHANGELOG.md
  Cargo.toml
  src/cipher/cipher.rs
  src/lib.rs
  src/tree/mod.rs
  src/tree/tests.rs
Labels: area:API, type:refactor

#98 Add new release tag
  Cargo.toml
Labels: type:refactor
