Repository dusk-network/Poseidon252, pull requests merged in 2020-08, with the labels that each got.

#44 Fix pi constraints & update lib docs
  Cargo.toml
  src/lib.rs
  src/merkle_proof/proof.rs
  src/sponge/sponge.rs
Labels: area:cryptography, type:refactor

#49 Implements #45 - Cipher ZK encrypt and decrypt
  CHANGELOG.md
  Cargo.toml
  src/cipher/zk.rs
Labels: type:feature

#50 Add copyright headers to .rs files
  src/cipher/cipher.rs
  src/cipher/error.rs
  src/cipher/mod.rs
  src/cipher/tests.rs
  src/cipher/zk.rs
  src/hashing_utils/mod.rs
  src/hashing_utils/poseidon_annotation.rs
  src/hashing_utils/scalar_storage.rs
  src/lib.rs
  src/merkle_lvl_hash/hash.rs
  src/merkle_lvl_hash/mod.rs
  src/merkle_proof/mod.rs
  src/merkle_proof/poseidon_branch.rs
  src/merkle_proof/proof.rs
  src/sponge/mod.rs
  src/sponge/pad.rs
  src/sponge/sponge.rs
  src/tree/mod.rs
Labels: documentation
