Repository dusk-network/Poseidon252, pull requests merged in 2020-09, with the labels that each got.

#52 Adding fixed hash length
  src/lib.rs
  src/perm_uses/fixed_hash.rs
  src/perm_uses/mod.rs
  src/perm_uses/pad.rs
  src/sponge/pad.rs
  src/sponge/sponge.rs
Labels: area:cryptography, type:feature

#59 Extract PI check from merkle_opening_gadget fn
  src/merkle_proof/proof.rs
  src/perm_uses/fixed_hash.rs
Labels: area:cryptography, type:refactor

#64 Bump deps & crate version
  CHANGELOG.md
  Cargo.toml
Labels: area:cryptography

#66 Migrate CI to Github actions, fix license headers
  .github/workflows/dusk_ci.yml
  .travis.yml
  src/cipher/cipher.rs
  src/cipher/error.rs
  src/cipher/mod.rs
  src/cipher/tests.rs
  src/cipher/zk.rs
  src/hashing_utils/mod.rs
  src/hashing_utils/poseidon_annotation.rs
  src/hashing_utils/scalar_storage.rs
  src/lib.rs
  src/merkle_lvl_hash/hash.rs
  src/merkle_lvl_hash/mod.rs
  src/merkle_proof/mod.rs
  src/merkle_proof/poseidon_branch.rs
  src/merkle_proof/proof.rs
  src/perm_uses/fixed_hash.rs
  src/perm_uses/mod.rs
  src/perm_uses/pad.rs
  src/sponge/mod.rs
  src/sponge/pad.rs
  src/sponge/sponge.rs
  src/tree/mod.rs
Labels: area:conf&build, area:documentation
